server:
  port: 3333

demo:
  keycloak:
    realmName: acme
    serverUrl: http://sso.tdlabs.local:8899/u/auth
    accountUrl: ${demo.keycloak.serverUrl}/realms/${demo.keycloak.realmName}/account
    externalBaseUrl: http://sso.tdlabs.local:3333

security:
  oauth2:
    client:
      # From OIDC app
      clientId: app-helloworld
      clientSecret: 57641931-9404-44e8-8109-d7978b8e6042
      # From Authorization Server's metadata
      accessTokenUri: ${demo.keycloak.serverUrl}/realms/${demo.keycloak.realmName}/protocol/openid-connect/token
      userAuthorizationUri: ${demo.keycloak.serverUrl}/realms/${demo.keycloak.realmName}/protocol/openid-connect/auth
      clientAuthenticationScheme: form
    resource:
      # from your Auth Server's metadata, check .well-known/openid-configuration
      userInfoUri: ${demo.keycloak.serverUrl}/realms/${demo.keycloak.realmName}/protocol/openid-connect/userinfo
      preferTokenInfo: false